#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v18
# autospec commit: f35655a
#
Name     : R-strucchange
Version  : 1.5.4
Release  : 60
URL      : https://cran.r-project.org/src/contrib/strucchange_1.5-4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/strucchange_1.5-4.tar.gz
Summary  : Testing, Monitoring, and Dating Structural Changes
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: R-strucchange-lib = %{version}-%{release}
Requires: R-sandwich
Requires: R-zoo
BuildRequires : R-sandwich
BuildRequires : R-zoo
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
regression models. strucchange features tests/methods from
	     the generalized fluctuation test framework as well as from
	     the F test (Chow test) framework. This includes methods to
	     fit, plot and test fluctuation processes (e.g., CUSUM, MOSUM,
	     recursive/moving estimates) and F statistics, respectively.
             It is possible to monitor incoming data online using
             fluctuation processes.
             Finally, the breakpoints in regression models with structural
             changes can be estimated together with confidence intervals.
             Emphasis is always given to methods for visualizing the data.

%package lib
Summary: lib components for the R-strucchange package.
Group: Libraries

%description lib
lib components for the R-strucchange package.


%prep
%setup -q -n strucchange
pushd ..
cp -a strucchange buildavx2
popd
pushd ..
cp -a strucchange buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1725292996

%install
export SOURCE_DATE_EPOCH=1725292996
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/strucchange/CITATION
/usr/lib64/R/library/strucchange/DESCRIPTION
/usr/lib64/R/library/strucchange/INDEX
/usr/lib64/R/library/strucchange/Meta/Rd.rds
/usr/lib64/R/library/strucchange/Meta/data.rds
/usr/lib64/R/library/strucchange/Meta/demo.rds
/usr/lib64/R/library/strucchange/Meta/features.rds
/usr/lib64/R/library/strucchange/Meta/hsearch.rds
/usr/lib64/R/library/strucchange/Meta/links.rds
/usr/lib64/R/library/strucchange/Meta/nsInfo.rds
/usr/lib64/R/library/strucchange/Meta/package.rds
/usr/lib64/R/library/strucchange/Meta/vignette.rds
/usr/lib64/R/library/strucchange/NAMESPACE
/usr/lib64/R/library/strucchange/NEWS
/usr/lib64/R/library/strucchange/R/strucchange
/usr/lib64/R/library/strucchange/R/strucchange.rdb
/usr/lib64/R/library/strucchange/R/strucchange.rdx
/usr/lib64/R/library/strucchange/data/Rdata.rdb
/usr/lib64/R/library/strucchange/data/Rdata.rds
/usr/lib64/R/library/strucchange/data/Rdata.rdx
/usr/lib64/R/library/strucchange/demo/tkmonitoring.R
/usr/lib64/R/library/strucchange/demo/tktesting.R
/usr/lib64/R/library/strucchange/doc/index.html
/usr/lib64/R/library/strucchange/doc/strucchange-intro.R
/usr/lib64/R/library/strucchange/doc/strucchange-intro.Rnw
/usr/lib64/R/library/strucchange/doc/strucchange-intro.pdf
/usr/lib64/R/library/strucchange/help/AnIndex
/usr/lib64/R/library/strucchange/help/aliases.rds
/usr/lib64/R/library/strucchange/help/paths.rds
/usr/lib64/R/library/strucchange/help/strucchange.rdb
/usr/lib64/R/library/strucchange/help/strucchange.rdx
/usr/lib64/R/library/strucchange/html/00Index.html
/usr/lib64/R/library/strucchange/html/R.css
/usr/lib64/R/library/strucchange/tests/Examples/strucchange-Ex.Rout.save
/usr/lib64/R/library/strucchange/tests/strucchange-tests.R
/usr/lib64/R/library/strucchange/tests/strucchange-tests.Rout.save

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/strucchange/libs/strucchange.so
/V4/usr/lib64/R/library/strucchange/libs/strucchange.so
/usr/lib64/R/library/strucchange/libs/strucchange.so
